import App from "./App.vue";
import Button from "./Button.vue";
import Card from "./Card.vue";
import Checkbox from "./Checkbox.vue";
import Chips from "./Chips.vue";
import Dialog from "./Dialog.vue";
import Drawer from "./Drawer.vue";
import Fab from "./Fab.vue";
import FormField from "./FormField.vue";
import GridList from "./GridList.vue";
import IconToggle from "./IconToggle.vue";
import LayoutGrid from "./LayoutGrid.vue";
import LinearProgress from "./LinearProgress.vue";
import List from "./List.vue";
import Menu from "./Menu.vue";
import Radio from "./Radio.vue";
import Select from "./Select.vue";
import Slider from "./Slider.vue";
import Snackbar from "./Snackbar.vue";
import Switch from "./Switch.vue";
import Tabs from "./Tabs.vue";
import Textfield from "./Textfield.vue";
import Toolbar from "./Toolbar.vue";

export default {
  install(Vue) {
    Vue.component(App.name, App);
    Vue.component(Button.name, Button);
    Vue.component(Card.name, Card);
    Vue.component(Checkbox.name, Checkbox);
    Vue.component(Chips.name, Chips);
    Vue.component(Dialog.name, Dialog);
    Vue.component(Drawer.name, Drawer);
    Vue.component(Fab.name, Fab);
    Vue.component(FormField.name, FormField);
    Vue.component(GridList.name, GridList);
    Vue.component(IconToggle.name, IconToggle);
    Vue.component(LayoutGrid.name, LayoutGrid);
    Vue.component(LinearProgress.name, LinearProgress);
    Vue.component(List.name, List);
    Vue.component(Menu.name, Menu);
    Vue.component(Radio.name, Radio);
    Vue.component(Select.name, Select);
    Vue.component(Slider.name, Slider);
    Vue.component(Snackbar.name, Snackbar);
    Vue.component(Switch.name, Switch);
    Vue.component(Tabs.name, Tabs);
    Vue.component(Textfield.name, Textfield);
    Vue.component(Toolbar.name, Toolbar);
  }
};